name: Video Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          sudo python3 -m pip install --upgrade pip
          sudo pip install yt-dlp

      - name: Download Video
        shell: bash
        run: |
          mkdir -p downloads
          # استفاده از ساده‌ترین دستور ممکن برای جلوگیری از تداخل فرمت‌ها
          yt-dlp -f "best" \
          --no-check-certificate \
          --geo-bypass \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Check Folder Content
        if: always()
        run: ls -R downloads/

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: video-output
          path: downloads/
          if-no-files-found: warn
