name: Video Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL'
        required: true
      quality:
        description: 'Quality (e.g. 1080, 720)'
        default: '1080'
      extension:
        description: 'Extension (mp4, mp3)'
        default: 'mp4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp

      - name: Download
        run: |
          mkdir -p downloads
          # دستور زیر با تنظیمات بهینه برای گیت‌هاب است
          yt-dlp -f "bestvideo[height<=${{ github.event.inputs.quality }}]+bestaudio/best" \
          --merge-output-format ${{ github.event.inputs.extension }} \
          --no-check-certificate \
          --geo-bypass \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: video-file
          path: downloads/
