name: Video Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Download Video
        run: |
          mkdir -p downloads
          yt-dlp -f "best" \
          --no-check-certificate \
          --geo-bypass \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: video-output
          path: downloads/
